(dp1
S'output'
p2
S'<class \'psycopg2.IntegrityError\'> insert or update on table "modificacion_bien_mueble" violates foreign key constraint "modificacion_bien_mueble_mbn_num_fkey"\nDETAIL:  Key (mbn_num)=(123121) is not present in table "bien_mueble".\n'
p3
sS'layer'
p4
S'/home/sandra/Documents/web2py/applications/sigulab2/controllers/inventarios.py'
p5
sS'code'
p6
S'<code object <module> at 0xae763608, file "/home/sandra/Documents/web2py/applications/sigulab2/controllers/inventarios.py", line 7>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/sandra/Documents/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/sandra/Documents/web2py/applications/sigulab2/controllers/inventarios.py", line 1390, in <module>\n  File "/home/sandra/Documents/web2py/gluon/globals.py", line 419, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/sandra/Documents/web2py/gluon/tools.py", line 3982, in f\n    return action(*a, **b)\n  File "/home/sandra/Documents/web2py/gluon/tools.py", line 3982, in f\n    return action(*a, **b)\n  File "/home/sandra/Documents/web2py/applications/sigulab2/controllers/inventarios.py", line 556, in detalles\n    user_id)\n  File "/home/sandra/Documents/web2py/applications/sigulab2/controllers/inventarios.py", line 527, in __agregar_modificar_bm\n    mbn_modifica_ficha = user\n  File "/home/sandra/Documents/web2py/gluon/packages/dal/pydal/objects.py", line 753, in insert\n    ret = self._db._adapter.insert(self, row.op_values())\n  File "/home/sandra/Documents/web2py/gluon/packages/dal/pydal/adapters/base.py", line 486, in insert\n    raise e\nIntegrityError: insert or update on table "modificacion_bien_mueble" violates foreign key constraint "modificacion_bien_mueble_mbn_num_fkey"\nDETAIL:  Key (mbn_num)=(123121) is not present in table "bien_mueble".\n\n'
p11
s.