(dp1
S'output'
p2
S"<type 'exceptions.IndexError'> list index out of range"
p3
sS'layer'
p4
S'/home/sandra/Documents/web2py/applications/sigulab2/controllers/inventarios.py'
p5
sS'code'
p6
S'<code object <module> at 0xb32e1bf0, file "/home/sandra/Documents/web2py/applications/sigulab2/controllers/inventarios.py", line 7>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/sandra/Documents/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/sandra/Documents/web2py/applications/sigulab2/controllers/inventarios.py", line 1390, in <module>\n  File "/home/sandra/Documents/web2py/gluon/globals.py", line 419, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/sandra/Documents/web2py/gluon/tools.py", line 3982, in f\n    return action(*a, **b)\n  File "/home/sandra/Documents/web2py/gluon/tools.py", line 3982, in f\n    return action(*a, **b)\n  File "/home/sandra/Documents/web2py/applications/sigulab2/controllers/inventarios.py", line 544, in detalles\n    bien = db(db.bien_mueble.bm_num == bm).select()[0]\n  File "/home/sandra/Documents/web2py/gluon/packages/dal/pydal/objects.py", line 2741, in __getitem__\n    row = self.records[i]\nIndexError: list index out of range\n'
p11
s.