(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> 'str' object has no attribute 'bm_espacio_fisico'"
p3
sS'layer'
p4
S'/home/sandra/Documents/web2py/applications/sigulab2/controllers/inventarios.py'
p5
sS'code'
p6
S'<code object <module> at 0xaf171968, file "/home/sandra/Documents/web2py/applications/sigulab2/controllers/inventarios.py", line 7>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/sandra/Documents/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/sandra/Documents/web2py/applications/sigulab2/controllers/inventarios.py", line 1390, in <module>\n  File "/home/sandra/Documents/web2py/gluon/globals.py", line 419, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/sandra/Documents/web2py/gluon/tools.py", line 3982, in f\n    return action(*a, **b)\n  File "/home/sandra/Documents/web2py/gluon/tools.py", line 3982, in f\n    return action(*a, **b)\n  File "/home/sandra/Documents/web2py/applications/sigulab2/controllers/inventarios.py", line 556, in detalles\n    user_id)\n  File "/home/sandra/Documents/web2py/applications/sigulab2/controllers/inventarios.py", line 499, in __agregar_modificar_bm\n    al espacio \\"{1}\\".".format(bm.mbn_nombre, bm.mbn_num.bm_espacio_fisico)\nAttributeError: \'str\' object has no attribute \'bm_espacio_fisico\'\n'
p11
s.